# Generated by Django 4.2.2 on 2023-06-25 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='value',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='type',
            field=models.CharField(choices=[('text', 'Text Field'), ('boolean', 'Checkbox'), ('choices', 'Dropdown List')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='text_value',
            field=models.CharField(blank=True, help_text='Product specification value (maximum of 255 words', max_length=255, null=True, verbose_name='value'),
        ),
        migrations.CreateModel(
            name='ProductChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='products.productspecification')),
            ],
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='choice_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productchoice'),
        ),
    ]
