# Generated by Django 3.2.16 on 2023-08-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
