# Generated by Django 3.2.16 on 2023-08-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
