# Generated by Django 3.2.16 on 2023-08-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20230808_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
