# Generated by Django 3.2.16 on 2023-08-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230809_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, help_text='SEO-friendly description for the category', verbose_name='SEO Description'),
        ),
    ]
